# Basic Information 
title: Xiao Wei
position: M.S. in Computer Science
affiliation: Duke University
affiliation_link: https://www.duke.edu/
affiliation_logo: ./assets/img/duke-logo-small.svg
email: x(dot)wei(at)duke(dot)edu
# email2: 

# Search Engine Optimization (SEO)
keywords: xiao wei, weixiao, x wei
# canonical: 
description: Xiao Wei is a master student at Duke University.

# The option is used to enable the template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=YOsAGGMAAAAJ&hl=en
# cv_link:
github_link: https://github.com/weeeixiao
linkedin: https://www.linkedin.com/in/xiao-wei-36a10b325/
# twitter:

# Images 
avatar: ./assets/img/formal_photo.jpg
favicon: ./assets/img/mylogo.ico
favicon_dark: ./assets/img/mylogo.ico

# Educations
duke_logo: ./assets/img/duke-logo.svg
sjtu_logo: ./assets/img/sjtu-logo-cropped.svg
umich_logo: ./assets/img/umich-logo.svg

# PRO
att_logo: ./assets/img/att.svg


# Footnotes
footnote: "2025 Xiao Wei"
#footnote_link:

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
